//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viji.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public Staff()
        {
            this.Parents = new HashSet<Parent>();
        }
    
        public int Staff_Id { get; set; }
        public string Staff_name { get; set; }
        public Nullable<int> Student_Id { get; set; }
    
        public virtual ICollection<Parent> Parents { get; set; }
        public virtual Student Student { get; set; }
    }
}
