//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viji.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Staffs = new HashSet<Staff>();
        }
    
        public int Student_Id { get; set; }
        public string Student_name { get; set; }
        public Nullable<int> Parent_Id { get; set; }
        public Nullable<int> Staff_Id { get; set; }
    
        public virtual ICollection<Staff> Staffs { get; set; }
    }
}
